stages:
  - build_backend
  - build_frontend
  - deploy

services:
  - docker:dind



variables:
  AWS_DEFAULT_REGION: "eu-west-1"  
  BACKEND_IMAGE: "tax-calc-backend"
  FRONTEND_IMAGE: "tax-calc-frontend"
  ECR_REPO_URL: "732656525333.dkr.ecr.eu-west-1.amazonaws.com"

before_script:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

build_backend:
  stage: build_backend
  script:
    - cd backend
    - echo "Building backend Docker image"
    - docker build -t $BACKEND_IMAGE .
    - echo "Tagging backend Docker image"
    - docker tag $BACKEND_IMAGE:latest $ECR_REPO_URL/$BACKEND_IMAGE:latest

build_frontend:
  stage: build_frontend
  script:
    - cd frontend
    - echo "Building frontend Docker image"
    - docker build -t $FRONTEND_IMAGE .
    - echo "Tagging frontend Docker image"
    - docker tag $FRONTEND_IMAGE:latest $ECR_REPO_URL/$FRONTEND_IMAGE:latest

deploy_backend:
  stage: deploy
  script:
    - echo "Logging in to AWS ECR"
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
    - echo "Pushing backend Docker image to ECR"
    - docker push $ECR_REPO_URL/$BACKEND_IMAGE:latest

deploy_frontend:
  stage: deploy
  script:
    - echo "Logging in to AWS ECR"
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
    - echo "Pushing frontend Docker image to ECR"
    - docker push $ECR_REPO_URL/$FRONTEND_IMAGE:latest
