image: docker:latest

services:
  - docker:dind

stages:
  - build_backend
  - build_frontend
  - push_backend_to_ecr
  - push_frontend_to_ecr
  - deploy_with_terraform

variables:
  ECR_REPO: "732656525333.dkr.ecr.eu-west-1.amazonaws.com/tax-calc-proxy"
  DOCKER_IMAGE_BACKEND: "backend"
  DOCKER_IMAGE_FRONTEND: "frontend"

before_script:
  - apk add --no-cache git openssh-client
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo "Installing AWS CLI"
  - apk add --no-cache aws-cli
  - echo "Logging in to AWS ECR"
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO

build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image"
    - cd backend
    - docker build -t $DOCKER_IMAGE_BACKEND .
    - docker images

build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend Docker image"
    - cd frontend
    - docker build --build-arg VP_ARTIFACTORY_TOKEN=${VP_ARTIFACTORY_TOKEN} -t $DOCKER_IMAGE_FRONTEND .

push_backend_to_ecr:
  stage: push_backend_to_ecr
  script:
    - echo "Building backend Docker image"
    - cd backend
    - docker build -t $DOCKER_IMAGE_BACKEND .
    - docker tag $DOCKER_IMAGE_BACKEND $ECR_REPO
    - docker images

    - echo "Pushing backend Docker image to ECR"
    - docker push $ECR_REPO


push_frontend_to_ecr:
  stage: push_frontend_to_ecr
  script:
    - echo "Building frontend Docker image"
    - cd frontend
    - docker build --build-arg VP_ARTIFACTORY_TOKEN=${VP_ARTIFACTORY_TOKEN} -t $DOCKER_IMAGE_FRONTEND .
    - docker tag $DOCKER_IMAGE_FRONTEND $ECR_REPO
    - docker images

    - echo "Pushing frontend Docker image to ECR"
    - docker push $ECR_REPO

deploy_with_terraform:
  stage: deploy_with_terraform
  script:
    - echo "Deploying backend to AWS with Terraform"
    - apk add --no-cache terraform
    - cd terraform/backend
    - terraform init
    - terraform apply -auto-approve

    - echo "Deploying frontend to AWS with Terraform"
    - cd terraform/frontend
    - terraform init
    - terraform apply -auto-approve
