image: docker:latest

services:
  - docker:dind

stages:
  - build_backend
  - build_frontend
  - push_to_ecr

variables:
  DOCKER_IMAGE_BACKEND: registry.gitlab.com/ayushi0903/tax-calculator/backend
  DOCKER_IMAGE_FRONTEND: registry.gitlab.com/ayushi0903/tax-calculator/frontend

before_script:
  - apk add --no-cache git openssh-client
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo "Installing AWS CLI"
  - apk add --no-cache aws-cli
  - echo "Logging in to AWS ECR"
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO

build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image"
    - cd backend
    - docker build -t $DOCKER_IMAGE_BACKEND --file Dockerfile .
    - docker images 

build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend Docker image"
    - cd frontend
    - docker build --build-arg VP_ARTIFACTORY_TOKEN=${VP_ARTIFACTORY_TOKEN} -t $DOCKER_IMAGE_FRONTEND:latest .


push_to_ecr:
  stage: push_to_ecr
  script:
    - echo "Pushing backend Docker image to ECR"
    - IMAGE_NAME=$DOCKER_IMAGE_BACKEND
    - IMAGE_TAG=latest
    - IMAGE_ID=$(docker images -q $IMAGE_NAME:$IMAGE_TAG)
    - if [ -z "$IMAGE_ID" ]; then echo "No Docker image found for $IMAGE_NAME:$IMAGE_TAG"; exit 1; fi
    - docker tag $IMAGE_ID $ECR_REPO/$IMAGE_NAME:$IMAGE_TAG
    - docker push $ECR_REPO/$IMAGE_NAME:$IMAGE_TAG

    - echo "Pushing frontend Docker image to ECR"
    - docker tag $DOCKER_IMAGE_FRONTEND:latest $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest
    - docker push $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest

