image: docker:latest

services:
  - docker:dind

stages:
  - build_backend
  - build_frontend
  - push_to_ecr

variables:
  ECR_REPO: "732656525333.dkr.ecr.eu-west-1.amazonaws.com/tax-calc-proxy"
  DOCKER_IMAGE_BACKEND: registry.gitlab.com/ayushi0903/tax-calculator/backend
  DOCKER_IMAGE_FRONTEND: registry.gitlab.com/ayushi0903/tax-calculator/frontend

before_script:
  - apk add --no-cache git openssh-client
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo "Installing AWS CLI"
  - apk add --no-cache aws-cli
  - echo "Logging in to AWS ECR"
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
  - AWS_AUTH=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
  - echo "AWS Authentication Token: $AWS_AUTH"
  - echo "$AWS_AUTH" | docker login --username AWS --password-stdin $ECR_REPO_URI

build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image"
    - cd backend
    - docker build -t $ECR_REPO/$DOCKER_IMAGE_BACKEND:latest .
    - docker images 

build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend Docker image"
    - cd frontend
    - docker build --build-arg VP_ARTIFACTORY_TOKEN=${VP_ARTIFACTORY_TOKEN} -t $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest .


push_to_ecr:
  stage: push_to_ecr
  script:
    - echo "ECR Repository URI: $ECR_REPO_URI"
    - echo "Docker Image Backend: $DOCKER_IMAGE_BACKEND"
    - echo "Docker Image Frontend: $DOCKER_IMAGE_FRONTEND"
    - echo "AWS CLI Version:"
    - aws --version


    - echo "Building backend Docker image"
    - cd backend
    - docker build -t $ECR_REPO/$DOCKER_IMAGE_BACKEND:latest .
    - docker images

    - echo "Pushing backend Docker image to ECR"
    - docker push $ECR_REPO/$DOCKER_IMAGE_BACKEND:latest

    - echo "Building frontend Docker image"
    - cd frontend
    - docker build -t $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest .
    - docker images

    - echo "Pushing frontend Docker image to ECR"
    - docker push $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest

   

