stages:
  - build_backend
  - build_frontend
  - push_to_ecr

variables:
  DOCKER_IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend
  DOCKER_IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend

before_script:
  - echo "Logging in to AWS ECR"
  - echo $AWS_SECRET_ACCESS_KEY | aws configure set aws_secret_access_key --stdin
  - echo $AWS_ACCESS_KEY_ID | aws configure set aws_access_key_id --stdin
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO

build_backend:
  stage: build_backend
  script:
    - echo "Building backend Docker image"
    - cd backend
    - docker build -t $DOCKER_IMAGE_BACKEND .
    - docker tag $DOCKER_IMAGE_BACKEND:latest $ECR_REPO/$DOCKER_IMAGE_BACKEND:latest

build_frontend:
  stage: build_frontend
  script:
    - echo "Building frontend Docker image"
    - cd frontend
    - docker build -t $DOCKER_IMAGE_FRONTEND .
    - docker tag $DOCKER_IMAGE_FRONTEND:latest $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest

push_to_ecr:
  stage: push_to_ecr
  script:
    - echo "Pushing backend Docker image to ECR"
    - docker push $ECR_REPO/$DOCKER_IMAGE_BACKEND:latest

    - echo "Pushing frontend Docker image to ECR"
    - docker push $ECR_REPO/$DOCKER_IMAGE_FRONTEND:latest

